### ISSUE TITLE
ImPlot::Histogram does not work with log scale on Y axis.  

### ISSUE THREAD

**Issue by Cazadorro** [epezent/implot#244] opened 2021-06-08 17:13 UTC
On demo for histogram, try right clicking and selecting y axis, then clicking log scale, the bounding "Theoretical" line remains (showing there *should* be something there), but the histogram itself disappears.  Manually setting `ImPlotAxisFlags_LogScale` also does the same thing, so it isn't just some demo bug.   Log scale seems to work fine for histograms on the X axis.

**Comment by epezent** [comment] 2021-06-08 19:18
Thanks. The issue is that the bottom of each bar is referenced to 0 on the y axis which can't be displayed on log scale. The result is that the entire bar is not drawn. We may need to convert 0s to a really small value to make this work. I'll have to think on it.

**Comment by epezent** [comment] 2021-06-09 03:32
Should be fixed:

![image](https://user-images.githubusercontent.com/29577475/121288678-937da000-c898-11eb-863c-5337982bbced.png)

**Closed by epezent** 2021-06-09 03:32 UTC
